### ISSUE TITLE
Typo in file pages/Profiile.jsx

### ISSUE THREAD

**Issue by karlosos** [PacktPublishing/Full-stack-Django-and-React#35]
On branch `chap15` there is a typo in file `src/pages/Profiile.jsx` should probably be `Profile.jsx`

https://github.com/PacktPublishing/Full-stack-Django-and-React/blob/chap15/social-media-react/src/pages/Profiile.jsx

**Comment by koladev32** [comment]
Hey @karlosos 

It is fixed now. Thanks for pointing the issue
