### ISSUE TITLE
While setting up postgres here are some of my challenges 

### ISSUE THREAD

**Issue by devshittu** [PacktPublishing/Full-stack-Django-and-React#44]
The book is an excellent resource for both beginners and experienced programmers. The book covers a wide range of topics, from basic syntax and programming concepts to more advanced techniques like web development and data analysis.

The authors provide clear explanations and practical examples for each topic, making it easy to follow along and apply the concepts in your own projects. The book is well-organized and easy to navigate, with helpful summaries and exercises at the end of each chapter.

One minor issue I encountered was that some of the code examples/steps did not work as expected, which caused some frustration and confusion. I don't know whether this is the right place to express my frustration and my workaround for people who might be facing similar issues.

My setup is 
PC Description:	Ubuntu 22.04.2 LTS
Postgres: PostgreSQL 15.2 (Ubuntu 15.2-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, 64-bit
Django = 4.0

```
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5342 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```

Then I followed a tutorial on [DigitalOcean](https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-20-04)
which showed some further tweaks to the 
```shell
ALTER ROLE core SET client_encoding TO 'utf8';
ALTER ROLE core SET default_transaction_isolation TO 'read committed';
ALTER ROLE core SET timezone TO 'UTC';
```
Then I got this error
```
psycopg2.errors.InsufficientPrivilege: permission denied for schema public
LINE 1: CREATE TABLE "django_migrations" ("id" bigserial NOT NULL PR....
```
Then I solved this using this page on [stackoverflow](https://stackoverflow.com/questions/74217259/create-table-django-migrations-id-bigint-not-null-prima) using this:
```shell
GRANT postgres TO core;
```

**Comment by ingarbi** [comment]
Also author uses wrong port

**Comment by koladev32** [comment]
@devshittu Thank you for sharing the solutions to the issues you encountered. 

There is also a correction to make concerning the port. It should be `5432` not `5342`.

**Comment by devshittu** [comment]
My pleasure!
