### ISSUE TITLE
Error after add router

### ISSUE THREAD

**Issue by thangduong3010** [PacktPublishing/Full-stack-Django-and-React#45]
Hello,
First of all, thank you for your amazing work. I've just started to read the book and have enjoyed it so far.

I'm at chapter 2, section Adding a router. After adding to the router like this, in file routers.py:
`router.register(r'user', UserViewSet, basename='user')
urlpatterns = [
*router.urls,
]`
Then I ran the server
`python manage.py runserver`

After that, made a GET request
`http://127.0.0.1:8000/api/user/`
then the following error occurred:

> Using the URLconf defined in CoreRoot.urls, Django tried these URL patterns, in this order:
> admin/
> The current path, api/user/, didn’t match any of these.

So I tried to figure the cause, and modified the urls.py file like this (the book does not mention to modify this file)
`urlpatterns = [ path("admin/", admin.site.urls),
    path("api/", include(("core.routers"))),
]
`

And I tried to request again, another error happened:

> TypeError at /api/user/
> 'str' object is not callable

I've wondered has someone else encountered this issue like I did?

**Comment by koladev32** [comment]
@chinne thank you for the solution. 

@thangduong3010  That is a missing part in the book actually. We will update it accordingly.
