### ISSUE TITLE
Initial User Migration Failed with Admin.0001 Dependency [Solved]

### ISSUE THREAD

**Issue by remyluslosius** [PacktPublishing/Full-stack-Django-and-React#46]
After creating the `UserManager` and `User` models, the migration failed with the error below.

`Migration admin.0001_initial is applied before its dependency core_user.0001_initial on database 'default'.`

I followed this [discussion thread's advice](https://gist.github.com/BaronKimaru/4a45928f6c5a35ea751d3007f2b7a8af) to delete/drop the database. 

`$ sudo su postgres`
`$  psql`

`postgres=# DROP DATABASE coredb;
`

Now, recreate the database. Remember the user 'core' still exists. There's no need to try to create it.

`postgres=# CREATE DATABASE coredb;`
`postgres=# ALTER ROLE core SET client_encoding TO 'utf8';`
`postgres=# ALTER ROLE core SET default_transaction_isolation TO 'read committed';`
`postgres=# ALTER ROLE core SET timezone TO 'UTC';`
`postgres=# ALTER DATABASE coredb OWNER TO core;`
`postgres=# GRANT ALL PRIVILEGES ON DATABASE coredb TO core;`

If you already  ran the "makemigrations" for core_user, simply  run `python manage.py migrate`

It works for me!

**Comment by rajat-packt** [comment]
Hey @koladev32 what do you think about this issue and user suggestion?
Let me know if I should add this to the README in order to bring it to other reader's attention too.

**Comment by koladev32** [comment]
@rajat-packt This is an interesting suggestion if the reader is learning/working with the book. We can point it in the README.md

**Comment by hallelx2** [comment]
Thank you very much for this. This solved my problem
