### ISSUE TITLE
insomnia test failed

### ISSUE THREAD

**Issue by samyrtusna** [PacktPublishing/Full-stack-Django-and-React#53]
I followed the book instructions step by step and when I got to insomnia test , I got a 404 not found error message telling me that : the current path, api/, didn't match any of these

**Comment by koladev32** [comment]
@samyrtusna can you send the URL you are using for the request? 

Also, the code in the `routers.py` file and the `urls.py` file.

**Comment by samyrtusna** [comment]
I found the issue, in the process of presentation in the book, the author forget to ad the API URL to urlpatterns in urls.py
