### ISSUE TITLE
Problem - Writing tests for authentication

### ISSUE THREAD

**Issue by SHYXIN** [PacktPublishing/Full-stack-Django-and-React#56]
Hello author, I am a Chinese and my English is not very good. While studying with your book, I learned about Chapter 5, Testing the REST API - Writing tests for authentication. Following the tests in the book, I encountered the following issues while writing core/auth/tests.py
Here are my code and errors

![image](https://github.com/user-attachments/assets/31b1756e-f59a-41ac-be6a-5d062916ad0a)

core/auth/tests.py
`import pytest
from rest_framework import status

from core.fixtures.user import user

class TestAuthenticationViewSet:

    endpoint = '/api/auth/'

    def test_login(self, client, user):
        data = {
            "username": user.username,
            "password": "test_password"
        }
        response = client.post(self.endpoint + "login/", data)

        assert response.status_code == status.HTTP_200_OK
        assert response.data['access']
        assert response.data['user']['id'] == user.public_id.hex
        assert response.data['user']['username'] == user.username
        assert response.data['user']['email'] == user.email
`

core/auth/tests.py

`
import pytest
from rest_framework import status

from core.fixtures.user import user

`

core/auth/viewsets/login.py
`

from rest_framework.response import Response
from rest_framework.viewsets import ViewSet
from rest_framework.permissions import AllowAny
from rest_framework import status
from rest_framework_simplejwt.exceptions import TokenError, InvalidToken
from core.auth.serializers import LoginSerializer

class LoginViewSet(ViewSet):
    serializer_class = LoginSerializer
    permission_classes = (AllowAny,)
    http_method_names = ['post']

    def create(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])

        return Response(serializer.validated_data, status=status.HTTP_200_OK)
`

You can view the complete code of this branch from here

https://github.com/SHYXIN/learn_full_stack/tree/bugfix-branch

Thank you

**Comment by koladev32** [comment]
Hi @SHYXIN 

For the username, you should use the user's email, `user.email`. if you want to have the mail and username for login, you need to add the EMAIL_FIELD attribute to the User model class like done at this line https://github.com/PacktPublishing/Full-stack-Django-and-React/blob/84fe42604f4ddc6bb9b4bdd99484476a099cefe7/core/user/models.py#L71

Sorry for the inconvenience.
