### ISSUE TITLE
cannot make post a comment for `http://127.0.0.1:8000/api/post/public_id/comment/`

### ISSUE THREAD

**Issue by naingkhanthtet** [PacktPublishing/Full-stack-Django-and-React#58]
I am at 'chapter 4, testing the comment feature in Insomnia' section. Previous tasks are fine such as creating a post with Bearer token. But I cannot specifically post a comment to social media post. After all the fixes, the error I am getting now is 
```
{
	"detail": "You do not have permission to perform this action."
}
```
Yes, I have tried re-logging in and made a POST request with fresh Bearer token.

**Comment by koladev32** [comment]
Hi @naingkhanthtet 

Can you please show me the code for the `CommentViewSet`class? Also, the code for `UserPermission`

**Comment by naingkhanthtet** [comment]
Hi @koladev32 
The problem has been solved. Thank you for your participation.
